# Generated by Django 2.0.7 on 2018-10-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.URLField(null=True),
        ),
    ]
